### ISSUE TITLE
Process Serialization with Inheritance

### ISSUE THREAD

**Issue by U8NWXD** [vivarium-collective/vivarium-core#159]
Currently, `Process.__init__()` saves off a copy of the parameters to `self._original_parameters`. Then when serializing, `Process.__getstate__()` returns `self._original_parameters` and `Process.__setstate__()` calls `self.__init__()` with the parameters.

This is problematic in class hierarchies where constructors change parameters. For example:

```python
class A(Process):

    def __init__(self, parameters):
        super().__init__({'2': parameters['1']})

a = A({'1': True})
a2 = pickle.loads(pickle.dumps(a))
```

Here, `A` receives a parameter under the key `1` but passes that parameter to `Process` under key `2`. 

Here's how the serialization/deserialization flow looks:

1. When an instance of `A` is serialized, `Process.__getstate__()` returns `{'2': True}`.
2. Then when we want to deserialize and get `a2`, `Process.__setstate__()` calls `self.__init__(parameters)`. However, it is `A.__init__()` that runs here, not `Process.__init__()`, so `A.__init__()` will be looking for a nonexistent key `1` in the parameters.

The fact that `A.__init__()` runs is correct. There could be code there that we need to run to initialize instance variables. The problem is that `a.__getstate__()` should be returning the original parameters passed to `A.__init__()`, not those passed to `Process.__init__()`.

Here are some possible solutions:

1. Add an optional parameter to `Process.__init__()` for the original subclass parameters, which will then be saved in `self._original_parameters`. This route will require that we update all constructors in an inheritance hierarchy to handle the new parameter.
2. Add a new `Process.save_parameters()` method that subclasses can call to save off their original parameters. With this approach, we will only have to change `Process` and the class at the bottom of the hierarchy. However, we will have to handle multiple calls to `Process.save_parameters()` since we only want to save the parameters from the child-most subclass.
3. Add a new special key to the `parameters` dictionary for the original parameters. If provided, `Process.__init__()` will save this in `self._original_parameters` instead of `parameters`.

I prefer approach (3) since I think it's most in line with how we pass other special configs to `Process`.

**Comment by eagmon** [comment]
I think we should avoid this swapping of parameter names, and maybe add asserts to make sure it is not being done. How about we assert that the keys going into the `super().__init__()` parameters are in the `defaults`? This won't rule out all cases -- for example if the `2` key in your example was in `defaults` -- but it will help avoid most of the bad cases.

**Comment by U8NWXD** [comment]
This swapping happens in subclasses of convenience kinetics, and I think it happens for a good reason. If you create a process to model e.g. glucose phosphorylation, you shouldn't force your users to specify all the reaction stoichiometry in the config. Since you as the process author know the stoichiometry, your process should be able to just accept a few parameters like rate constants and then build the parameter dict that convenience kinetics expects.

**Comment by eagmon** [comment]
So (3) would be something like:
```
super().__init__({'2': parameters['1'], '_parameters': parameters})
```
That seems easy enough?
