### ISSUE TITLE
Remove MultiInvoke?

### ISSUE THREAD

**Issue by U8NWXD** [vivarium-collective/vivarium-core#75]
We currently define a `MultiInvoke` class in `experiment.py`:

https://github.com/vivarium-collective/vivarium-core/blob/a92f8eb87d70285cce243f55aea765596aba271e/vivarium/core/experiment.py#L124

However, I can't find any usages of it in `vivarium-collective` or in my wcEcoli work. It seems that we're handling parallel processing using `ParallelProcess` instead.

Can `MultiInvoke` be removed?

**Comment by U8NWXD** [comment]
@eagmon @prismofeverything what do you think?

**Comment by eagmon** [comment]
I think we can remove this. It looks like it might be left over from when @prismofeverything first introduced parallel processes.  It came to this repo with the initial migration from the old vivarium.

**Comment by U8NWXD** [comment]
Sounds good.. I'm updating the docs now. I'll delete `MultiInvoke` in my PR with the documentation updates
